### ISSUE TITLE
Unable to change colour of Updub and Downdub buttons among other things

### ISSUE THREAD

**Issue by AuesomeMan3840** [sinfulBA/DubX-Script#35]
I'm making a theme for the room I go on, and I'm basing it of the Plug.DJ theme that is in DubX already, however for whatever reason, I'm unable to change the colour of the updub and downdub buttons, as well as the header and the player bar.

**Comment by coryshaw1** [comment]
How are you selecting it?

```css
#player-controller .right ul li .dubup.voted
```

If that's how your selector is then have you tried changing to whatever CSS properties to use `!important` like so:

```css
#player-controller .right ul li .dubup.voted {
    background: rebeccapurple !important;
}
```

Are these the only parts that are giving you trouble, or is none of your styling showing?
